[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
chirp_staking = "5ghCYkAfKSYZxuWi3ACcWviF9d7zCE8XKf2LD4hajMcL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/jmf/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
